package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        expect {
            param("env.DRIVER", "org.h2.Driver")
        }
        update {
            password("env.DRIVER", "credentialsJSON:b45a8f24-3283-4596-8648-fab11a3314f8", display = ParameterDisplay.HIDDEN)
        }
        expect {
            param("env.PASSWORD", "")
        }
        update {
            password("env.PASSWORD", "credentialsJSON:c3ac330a-ef9e-40b3-af36-16407dddf5fc", display = ParameterDisplay.HIDDEN)
        }
        expect {
            param("env.URL", "jdbc:h2:mem:test;MODE=Oracle;")
        }
        update {
            password("env.URL", "credentialsJSON:70a3dfeb-6cff-48f6-857e-843bf160b113", display = ParameterDisplay.HIDDEN)
        }
    }
}
