DROP TABLE knolder IF EXISTS;
DROP TABLE blog IF EXISTS;
DROP TABLE knolx IF EXISTS;
DROP TABLE webinar IF EXISTS;
DROP TABLE techhub IF EXISTS;
DROP TABLE all_time_reputation IF EXISTS;
DROP TABLE monthly_reputation IF EXISTS;
DROP TABLE quarterly_reputation IF EXISTS;
